### ISSUE TITLE
Mac build is not notarized

### ISSUE THREAD

**Issue by BSVogler** [molovol/MoloVol#107]
I noticed that the app is not notarized. When attempting to launch you will get an error message. You need to obtain a paid Apple developer membership to notarize the build.

Alternatively, you can open the app while holding alt to enable the option to launch it anyways. I think this should be documented for people who are not aware of that.

**Comment by jmaglic** [comment]
There are currently no plans on getting an Apple developer ID. There is a cost involved and because we're operating on a no-profit basis and we aren't externally funded, we would have to pay out of our own pockets.

I have, however, added some details about the installation on the [website](https://molovol.com) as well as in the [readme](https://github.com/molovol/MoloVol#readme). I hope that it is noticeable enough.
