### ISSUE TITLE
Surface area is not output in command line interface

### ISSUE THREAD

**Issue by hyotankuzure** [molovol/MoloVol#142]
### Description

Surface area is not output in command line interface.

### How to reproduce the issue
-input
\desktop\MoloVol_windows_v1.1.1>molovol -r 1.2 -g 0.2 -fs ./inputfile/example_C60.xyz -q -o surf_vdw,vol_vdw,depth

-output
<INPUT>
Octree depth: 4
<VOLUME>
Van der Waals volume: 528.624000 A^3

-system
windows 10 64bit
MoloVol ver. 1.1.1

### Proposed change

I would like to change it to output the surface area.

**Comment by jmaglic** [comment]
Thanks for reaching out! Fortunately, there is an easy fix. The surface values are not showing because surface calculations have to be manually enabled. Just add `-sf` or `--surface` to the end of the command.

```shell
$ molovol -r 1.2 -g 0.2 -fs ./inputfile/example_C60.xyz -q -o surf_vdw,vol_vdw,depth -sf
```

This should output:

```
<INPUT>
Octree depth: 4
<VOLUME>
Van der Waals volume: 528.624000 A^3
The-World-Traveller:build-experiment jmaglic$ ./MoloVol -r 1.2 -g 0.2 -fs ../inputfile/example_C60.xyz -q -o surf_vdw,vol_vdw,depth -sf
<INPUT>
Octree depth: 4
<VOLUME>
Van der Waals volume: 528.624000 A^3
<SURFACE>
Van der Waals surface: 400.103524 A^2
```

I hope that fixes your issue. I'll look into whether we can make the manual or interface clearer to avoid such confusion.
